name: GitHub CI
on:
  push:
    branches: [ 0.11 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Cache Toolchain
       uses: actions/cache@v2
       env:
         cache-name: cache-toolchain
       with:
         path: |
           **/toolchain
         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build_toolchain.sh') }}
         restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build_toolchain.sh') }}

     - name: Build i686-elf-gcc Toolchain
       run: |
         cd ./toolchain/
         chmod +x ./build_toolchain.sh
         ./build_toolchain.sh

     - name: Install Dependencies
       run: |
         sh ./scripts/install_deps.sh
     
     - name: Build PlatypusOS
       run: |
         make
         
     - name: Upload Build Artifact
       uses: actions/upload-artifact@v2.2.3
       with:
         name: PlatypusOS-Build.iso
         path: PlatypusOS.iso
         if-no-files-found: warn
